config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome', as: :home
  get 'portfolio' => 'pages#portfolio', as: :portfolio
  get 'about' => 'pages#about', as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  def portfolio
    @buildings = Building.all
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PORTFOLIO VERSION 2!!!</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="app/assets/stylesheets/pages.scss">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;300;500;700&display=swap" rel="stylesheet"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="topnav">
      <%= link_to "Home", home_path %>
      <%= link_to "Portfolio", portfolio_path %>
      <%= link_to "About", about_path %>
      <a href="#contact">Contact</a>
    </div>
    <%= yield %>
    <footer class="footer">
      <p>
        Author: Snoop Dogg<br>
        <a href="#">snoop@dogg.com</a>
      </p>
      <div class="social-links">
        <img src="https://cdn-icons-png.flaticon.com/512/2111/2111463.png" alt="">
        <img src="https://cdn-icons-png.flaticon.com/512/733/733547.png" alt="">
        <img src="https://cdn-icons-png.flaticon.com/512/1384/1384060.png" alt="">
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About me</h1>
  <div class="images">
    <img src="https://cdn.britannica.com/69/160969-050-F18C2AAC/Daniel-Craig-James-Bond-Casino-Royale.jpg" alt="">
  </div>
  <p>This is me</p>
</div>

app/views/pages/portfolio.html.erb
<div class="container">
  <section class="main">
    <h2>My best work:</h2>
    <img src="https://i.kym-cdn.com/entries/icons/original/000/002/017/n307683349254_180.jpg" alt="">
  </section>
  <section class="my-work">
    <h3>Here is a list of all my work:</h3>
    <% @buildings.each do |b| %>
      <div class="images"><%= image_tag b.image %></div>
      <%= b.title %>
    <% end %>
  </section>
</div>

app/views/pages/welcome.html.erb
<html>
  <body>
    <div style="padding-left:16px">
      <h2>Hello, my name is Matt Butler</h2>
      <p>This is my portfolio</p>
    </div>
    <section>
      <div class="btn">
        <%= link_to "View my work", portfolio_path %>
      </div>
    </section>
  </body>

</html>